- platform: attributes
  friendly_name: "Batterie"
  attribute: battery
  unit_of_measurement: "V"
  entities:
    - climate.leq0584727
    - climate.meq0182042
    - climate.meq0182064
    - climate.meq0182081
    - climate.meq0182095
    - climate.meq0182097
    - climate.meq0182100
    - climate.meq0182105
    - climate.meq0182106
    - climate.meq0182136
    - climate.meq0182137
    - climate.meq0182655
    - climate.meq0233504


      #    - binary_sensor.barbarafenster_state
      #    - binary_sensor.dominikfenster_state
      #    - binary_sensor.hannesfenster_state
      #    - binary_sensor.hannestuer_state
      #    - binary_sensor.kuechefenster_state
      #    - binary_sensor.schlafzimmer_links_state
      #    - binary_sensor.schlafzimmer_rechts_state
      #    - binary_sensor.sparesco_state
      #    - binary_sensor.vorzimmerogfenster_state
      #    - binary_sensor.windfangtuer_state
      #    - binary_sensor.wohnzimmertuer_state
