- platform: mqtt
  state_topic: "hm/status/Gaszaehler/GAS_POWER"
  name: "gas_power"
  unit_of_measurement: "m3"
  value_template: '{{ value_json.val }}'
- platform: mqtt
  state_topic: "hm/status/Gaszaehler/GAS_ENERGY_COUNTER"
  name: "gas_energy_counter"
  unit_of_measurement: "m3"
  value_template: '{{ value_json.val }}'
- platform: template
  sensors:
    waschmaschine_status:
      entity_id: sensor.leq0574052_power
      friendly_name: Waschmaschine
      value_template: >
        {%- if states.sensor.leq0574052_power.state|float > 5 -%}
        Aktiv
        {%- elif states.sensor.leq0574052_power.state|float >= 1 -%}
        Standby
        {%- else -%}
        Aus
        {%- endif -%}
