- platform: mqtt
  state_topic: "hm/status/Gaszaehler/GAS_POWER"
  name: "gas_power"
  unit_of_measurement: "m3"
  value_template: '{{ value_json.val }}'
- platform: mqtt
  state_topic: "hm/status/Gaszaehler/GAS_ENERGY_COUNTER"
  name: "gas_energy_counter"
  unit_of_measurement: "m3"
  value_template: '{{ value_json.val }}'
- platform: mqtt
  state_topic: "hm/status/Stromzaehler/POWER"
  name: "strom_power"
  unit_of_measurement: "W"
  value_template: "{{ value_json.val }}"
- platform: template
  sensors:
    sauna_heizung_valve:
      entity_id: climate.sauna_heizung
      value_template: >
        {%- if states.climate.sauna_heizung.attributes is defined %}
        {{ states.climate.sauna_heizung.attributes.valve }}
        {%- else %}
        0
        {%- endif %}
      unit_of_measurement: '%'
#        '{{ states.climate.sauna_heizung.attributes.valve }}'
    bad_heizung_valve:
      entity_id: climate.badheizung
      value_template: '{{ states.climate.badheizung.attributes.valve | default(0) }}'
      unit_of_measurement: '%'
    barbara_heizung_valve:
      entity_id: climate.barbaraheizung
      value_template: '{{ states.climate.barbaraheizung.attributes.valve | default(0) }}'
      unit_of_measurement: '%'
    dominik_heizung_valve:
      entity_id: climate.dominikheizung
      value_template: '{{ states.climate.dominikheizung.attributes.valve | default(0) }}'
      unit_of_measurement: '%'
    esszimmer_heizung_valve:
      entity_id: climate.esszimmerheizung
      value_template: '{{ states.climate.esszimmerheizung.attributes.valve | default(0) }}'
      unit_of_measurement: '%'
    vorzimmerog_heizung_valve:
      entity_id: climate.vorzimmerogheizung
      value_template: '{{ states.climate.vorzimmerogheizung.attributes.valve | default(0) }}'
      unit_of_measurement: '%'
    hannes_heizung_valve:
      entity_id: climate.hannesheizung
      value_template: '{{ states.climate.hannesheizung.attributes.valve | default(0) }}'
      unit_of_measurement: '%'
    kueche_heizung_valve:
      entity_id: climate.kuecheheizung
      value_template: '{{ states.climate.kuecheheizung.attributes.valve | default(0) }}'
      unit_of_measurement: '%'
    schlafzimmer_links_heizung_valve:
      entity_id: climate.schlafzimmerheizunglinks
      value_template: '{{ states.climate.schlafzimmerheizunglinks.attributes.valve | default(0) }}'
      unit_of_measurement: '%'
    schlafzimmer_rechts_heizung_valve:
      entity_id: climate.schlafzimmerheizungrechts
      value_template: '{{ states.climate.schlafzimmerheizungrechts.attributes.valve | default(0) }}'
      unit_of_measurement: '%'
    vorzimmer_heizung_valve:
      entity_id: climate.vorzimmerheizung
      value_template: '{{ states.climate.vorzimmerheizung.attributes.valve | default(0) }}'
      unit_of_measurement: '%'
    windfang_heizung_valve:
      entity_id: climate.windfangheizung
      value_template: '{{ states.climate.windfangheizung.attributes.valve | default(0) }}'
      unit_of_measurement: '%'
    wohnzimmer_heizung_valve:
      entity_id: climate.wohnzimmerheizung
      value_template: '{{ states.climate.wohnzimmerheizung.attributes.valve | default(0) }}'
      unit_of_measurement: '%'
- platform: template
  sensors:
    waschmaschine_status:
      entity_id: sensor.leq0574052_power
      friendly_name: Waschmaschine
      value_template: >
        {%- if states.sensor.leq0574052_power.state|float > 5 -%}
        Aktiv
        {%- elif states.sensor.leq0574052_power.state|float >= 1 -%}
        Standby
        {%- else -%}
        Aus
        {%- endif -%}
