# Sauna
- platform: mold_indicator
  name: mold_sauna
  indoor_temp_sensor: sensor.leq0868600_temperature
  indoor_humidity_sensor: sensor.leq0868600_humidity
  outdoor_temp_sensor: sensor.leq0798807_temperature
  calibration_factor: 3.375

# Schlafzimmer
- platform: mold_indicator
  name: mold_schlafzimmer
  indoor_temp_sensor: sensor.leq0868021_temperature
  indoor_humidity_sensor: sensor.leq0868021_humidity
  outdoor_temp_sensor: sensor.leq0798807_temperature
  calibration_factor: 2.0

# Bad
- platform: mold_indicator
  name: mold_bad
  indoor_temp_sensor: sensor.leq0122248_temperature
  indoor_humidity_sensor: sensor.leq0122248_humidity
  outdoor_temp_sensor: sensor.leq0798807_temperature
  calibration_factor: 2.0

# Wohnzimmer
- platform: mold_indicator
  name: mold_wohnzimmer
  indoor_temp_sensor: sensor.leq0868616_temperature
  indoor_humidity_sensor: sensor.leq0868616_humidity
  outdoor_temp_sensor: sensor.leq0798807_temperature
  calibration_factor: 2.0

# Kueche
- platform: mold_indicator
  name: mold_kueche
  indoor_temp_sensor: sensor.leq0867920_temperature
  indoor_humidity_sensor: sensor.leq0867920_humidity
  outdoor_temp_sensor: sensor.leq0798807_temperature
  calibration_factor: 2.0
