- platform: 'bayesian'
  name: 'in_bed'
  prior: 0.25
  probability_threshold: 0.95

  observations:
    - entity_id: 'sensor.sun'
      prob_given_true: 0.7
      platform: 'state'
      to_state: 'below_horizon'
    - entity_id: 'binary_sensor.vorzimmerogbewegungsmelder_motion'
      prob_given_true: 0.5
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'off'
    - entity_id: 'binary_sensor.hannesbewegungsmelder_motion'
      prob_given_true: 0.5
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'off'
    - entity_id: 'binary_sensor.esszimmerbewegungsmelder_motion'
      prob_given_true: 0.5
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'off'
    - entity_id: 'switch.pangea'
      prob_given_true: 0.3
      prob_given_false: 0.6
      platform: 'state'
      to_state: 'on'

