#sequence:
#  - service: media_player.sonos_snapshot
#  - service: media_player.sonos_group_players
#    data:
#      entity_id: media_player.wohnzimmer
#  - service: media_player.volume_set
#    data:
#      entity_id: media_player.wohnzimmer
#      volume_level: 0.6
#  - service: tts.google_say
#    data_template:
#      entity_id: media_player.wohnzimmer
#      message: "{{ message }}"
#  - delay:
#      seconds: 10
#  - service: media_player.sonos_restore
# > SONOS TTS
alias: SONOS TTS
sequence:
  #  - service: media_player.sonos_group_players
  #    data:
  #      entity_id: "{{ 'media_player.' ~ where }}"
  - service: media_player.sonos_snapshot
    data_template:
      entity_id: "{{ 'media_player.' ~ where }}"
      with_group: yes
  - service: media_player.sonos_unjoin
    data_template:
      entity_id: "{{ 'media_player.' ~ where }}"
  - service: media_player.volume_set
    data_template:
      entity_id: "{{ 'media_player.' ~ where }}"
      volume_level: 0.70
  #- service: tts.google_say
  - service: tts.amazon_polly_say
    data_template:
      entity_id: "{{ 'media_player.' ~ where }}"
      message: "<speak>{{ message }}</speak>"
      language: "de-DE"
  # Workout the length of the media
  - delay:
      seconds: 1
  - delay: >-
      {% set duration = states.media_player[where].attributes.media_duration %}
      {% if duration > 0 %}
        {% set duration = duration - 1 %}
      {% endif %}
      {% set seconds = duration % 60 %}
      {% set minutes = (duration / 60)|int % 60 %}
      {% set hours = (duration / 3600)|int %}
      {{ "%02i:%02i:%02i"|format(hours, minutes, seconds)}}
  - service: media_player.sonos_restore
    data_template:
      entity_id: "{{ 'media_player.' ~ where }}"
      with_group: yes
