alias: Wetteransage
sequence:
  - service: media_player.sonos_snapshot
    data_template:
      entity_id: "media_player.{{ where }}"
  - service: media_player.volume_set
    data:
      entity_id: media_player.sauna
      volume_level: 0.2
  - service: tts.google_say
    data_template:
      entity_id: "media_player.{{ where }}"
      message: "Guten Morgen {{ who }}. Das Wetter heute: {{ states('sensor.wetter_heute') }}"
      cache: false
  - delay: "00:00:{{ states.media_player[where].attributes.media_duration | int }}"
  - service: media_player.sonos_restore
    data_template:
      entity_id: "media_player.{{ where }}"
