- name: Hannes Movie
  entities:
    light.p16tw_01:
      state: off
    light.p16tw_02:
      state: off
    switch.hannesdeckenlicht: off
- name: Hannes Normal
  entities:
    light.p16tw_01:
      state: on
      brightness: 100
    light.p16tw_02:
      state: on
      brightness: 100
    switch.hannesdeckenlicht: on
