- alias: "IP Address changed"
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.hauscyberkovat
  condition:
    - condition: template
      value_template: "{% if states.automation.ha_startup.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.ha_startup.attributes.last_triggered)) > 5*60 }}  {% else %}false{% endif %}"
    - condition: template
      value_template: '{{ states.sensor.hauscyberkovat.state != "unknown" }}'
  action:
    - service: notify.slack
      data_template:
        message: Home IP Address was changed. The new home IP address is "{{ states('sensor.hauscyberkovat') }}"
