# Set the Internet switch to on upon startup
- alias: 'HA Startup'
  initial_state: True
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.slack
      data_template:
        message: >
          Home Assistant {{ states("sensor.current_version") }} starting up.
- alias: 'HA Shutdown'
  initial_state: True
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: notify.slack
      data_template:
        message: >
          Home Assistant {{ states("sensor.current_version") }} going down.
