- alias: "Homematic Switches died"
  initial_state: True
  trigger:
    - platform: state
      entity_id: switch.meq0712568
      to: "unavailable"
      for:
        minutes: 5
    - platform: state
      entity_id: switch.leq0531146
      to: "unavailable"
      for:
        minutes: 5
  action:
    - service: notify.slack
      data_template:
        message: >
          Homematic {{ trigger.entity_id }} is {{ trigger.to_state.state }}. Restarting HASS.
    - service: homeassistant.restart
