---
- alias: 'Heizungssteuerung'
  initial_state: false
  trigger:
    # This one triggers every time we go above 15% valve opening e.g. someone pressed the boost button
    - platform: template
      value_template: "{{ states.climate|rejectattr('state', 'equalto', 'unknown')|map(attribute='attributes.valve')|map('int')|sum >= 15 }}"
      # This one mainly triggers to turn the heating off again.
    - platform: time_pattern
      minutes: '/15'
      seconds: 0
  condition:
    - condition: state
      entity_id: switch.heizsaison
      state: 'on'
  action:
    - service_template: >
        {% if states.climate|rejectattr('state', 'equalto', 'unknown')|map(attribute='attributes.valve')|map('int')|sum >= 20*3 %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      entity_id: switch.meq0712568

- alias: 'Heizungssteuerung on'
  initial_state: true
  trigger:
    # This one triggers every time we go above 60% valve opening e.g. someone pressed the boost button
    - platform: numeric_state
      entity_id: sensor.heizbedarf
      above: 60
  condition:
    - condition: state
      entity_id: switch.heizsaison
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.meq0712568

- alias: 'Heizungssteuerung off'
  initial_state: true
  trigger:
    # This one triggers every time we go below 60% valve opening
    - platform: numeric_state
      entity_id: sensor.heizbedarf
      below: 60
  condition:
    - condition: state
      entity_id: switch.heizsaison
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.meq0712568
