- alias: "Heizung daily reset"
  initial_state: True
  trigger:
    - platform: time
      at: "19:00:00"
  condition:
    - condition: state
      entity_id: switch.heizsaison
      state: "on"
  action:
    - service: climate.set_operation_mode
      data:
        operation_mode: "auto"
    - service: notify.slack
      data_template:
        message: >
          Setze Heizungen auf Automatik zurueck.
