# Notify if mqtt connection to Homematic CCU is lost
- alias: Homematic MQTT Notification
  initial_state: True
  trigger:
    - platform: state
      entity_id: switch.hm_connected
      from: "on"
      to: "off"
  action:
    service: notify.hannes
    data_template:
      message: MQTT Connection to Homematic CCU has been lost.
