- alias: "Tuerklingel"
  initial_state: True
  trigger:
    - platform: event
      event_type: homematic.keypress
      event_data:
        name: Tuerklingel
        channel: 4
        param: PRESS_SHORT
    - platform: event
      event_type: homematic.keypress
      event_data:
        name: Tuerklingel
        channel: 4
        param: PRESS_LONG
  action:
    - service: script.tuerklingel
