- alias: "Update config if travis build is successfull"
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.travis_build_label
  condition:
    - condition: state
      entity_id: sensor.travis_status
      state: "Success"
  action:
    # TODO: This script needs to be written somehow...
    - service: script.get_latest_config
