- alias: "Vacuum: Starte Staubsauger bei Abwesenheit"
  initial_state: True
  trigger:
    - platform: state
      entity_id: group.personen
      from: "home"
      to: "not_home"
      for:
        minutes: 20
  condition:
    condition: and
    conditions:
      - condition: time
        after: "09:00:00"
        before: "16:00:00"
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: numeric_state
        entity_id: sensor.petsi_battery
        above: 95
  action:
    - service: notify.slack
      data_template:
        message: >
          Alle Weg. Aktiviere Staubsauger.
    - service: homeassistant.turn_on
      data:
        entity_id: switch.petsi_clean
- alias: "Vacuum: Notify on errors"
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.petsi_state
      to: "Error"
  action:
    - service: notify.slack
      data_template:
        message: >
          Petsi had an error. It got lost in action.
- alias: "Vacuum: Notify on success"
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.petsi_state
      from: "Searching Homebase"
      to: "On homebase: Trickle Charging"
  action:
    - service: notify.slack
      data_template:
        message: >
          Petsi returned home safely.
