entities:
  - binary_sensor.leq1085620_state
  - binary_sensor.leq1177637_state
  - binary_sensor.meq0172089_state
  - binary_sensor.meq0186561_state
  - binary_sensor.meq0186563_state
  - binary_sensor.meq0186607_state
  - binary_sensor.meq0186623_state
  - binary_sensor.meq0186642_state
  - binary_sensor.meq0186709_state
  - binary_sensor.meq0186720_state
