entities:
  - binary_sensor.hannesbewegungsmelder_motion
  - binary_sensor.hannesfenster_state
  - binary_sensor.hannestuer_state
  - media_player.kodi_hannes
  - sensor.hannesbewegungsmelder_brightness
  - climate.hannesheizung
  - switch.nas
  - switch.pangea
  - switch.ccu
  - binary_sensor.sco_spare
  - binary_sensor.sparesco_state
  - light.it_stecker_3
  - switch.hannesdeckenlicht
  - light.p16tw_01
  - light.p16tw_02
