entities:
  - binary_sensor.meq0186642_state
  - climate.meq0182095
  - media_player.kuche
  - sensor.leq0531373_current
  - sensor.leq0531373_energy_counter
  - sensor.leq0531373_frequency
  - sensor.leq0531373_power
  - sensor.leq0531373_voltage
  - sensor.leq0867920_humidity
  - sensor.leq0867920_temperature
  - sensor.mold_kueche
  - switch.leq0531373
