entities:
  - sensor.cpu_load_total
  - sensor.memory_usage_real
  - sensor.network_up
  - sensor.status_sda
  - sensor.status_sdb
  - sensor.status_smart_sda
  - sensor.status_smart_sdb
  - sensor.status_volume_1
