icon: mdi:lan-connect
view: yes
entities:
  - group.internet
  - group.torrent
  - group.system
  - group.nas
  - group.automatik
  - group.batterien
  - group.valves
  - group.all_automations
  - group.monitoring
