---
entities:
  - automation.luftentfeuchter
  - binary_sensor.luftentfeuchter_status
  - climate.leq0584727
  - media_player.sauna
  - sensor.leq0531146_current
  - sensor.leq0531146_energy_counter
  - sensor.leq0531146_frequency
  - sensor.leq0531146_power
  - sensor.leq0531146_voltage
  - sensor.leq0868600_humidity
  - sensor.leq0868600_temperature
  - sensor.luftentfeuchter_on_today
  - sensor.mold_sauna
  - sensor.stats_sauna_humidity_mean
  - switch.leq0531146
