icon: mdi:magnet-on
entities:
  - sensor.transmission_down_speed
  - sensor.transmission_status
  - sensor.transmission_up_speed
  - sensor.sonarr_queue
  - sensor.sonarr_upcoming
  - sensor.radarr_upcoming
  - sensor.radarr_status
