entities:
  - binary_sensor.wallpanel_status
  - climate.vorzimmerheizung
  - device_tracker.petsi
  - sensor.petsi_battery
  - sensor.petsi_capacity
  - sensor.petsi_state
  - sensor.wallpanel_battery
  - switch.it_stecker_1
  - switch.petsi_clean
  - switch.petsi_dock
  - switch.petsi_find
