entities:
  - sensor.gas_energy_counter
  - sensor.gas_power
  - sensor.heizbedarf
  - sensor.leq0574052_current
  - sensor.leq0574052_energy_counter
  - sensor.leq0574052_frequency
  - sensor.leq0574052_power
  - sensor.leq0574052_voltage
  - sensor.meq0705859_energy_counter
  - sensor.meq0705859_gas_energy_counter
  - sensor.meq0705859_gas_power
  - sensor.meq0705859_power
  - sensor.meq0705859_power
  - sensor.meq0705863_energy_counter
  - sensor.meq0705863_gas_energy_counter
  - sensor.meq0705863_gas_power
  - sensor.meq0705863_gas_power
  - sensor.meq0705863_power
  - sensor.strom_power
  - sensor.waschmaschine_status
  - switch.leq0574052
  - switch.meq0712568
  - switch.mqtt_wirtschaftsraum_therme
