entities:
  - binary_sensor.wohnzimmertuer_state
  - climate.wohnzimmerheizung
  - light.fernsehlampe
  - media_player.kodi_wohnzimmer
  - media_player.wohnzimmer
  - sensor.mold_wohnzimmer
  - sensor.wohnzimmertemperatur_humidity
  - sensor.wohnzimmertemperatur_temperature
  - switch.wohnzimmer_tv
