entities:
  - binary_sensor.meq0186561_state
  - climate.meq0182042
  - light.fernsehlampe
  - media_player.kodi_wohnzimmer
  - media_player.wohnzimmer
  - sensor.leq0868616_humidity
  - sensor.leq0868616_temperature
  - sensor.mold_wohnzimmer
  - switch.wohnzimmer_tv
