---
hass.somebody_home:
  speech:
    text: >
      {% if is_state("device_tracker.barbara", "home") or
      is_state("device_tracker.cyberkov", "home") or is_state("group.bewegungsmelder", "on") -%}
      Ja. {% if is_state("device_tracker.barbara", "home") and
      is_state("device_tracker.cyberkov", "home") -%}
      Barbara und Hannes sind
      {%- elif is_state("device_tracker.cyberkov", "home") -%}
      Hannes ist
      {%- elif is_state("device_tracker.barbara", "home") -%}
      Barbara ist
      {%- endif %} zuhause.{%- else -%} Nein. {%- endif %}
      {%- if is_state("switch.guests", "on") %}Wir haben derzeit Gäste im Haus.{%- endif %}
      Die Alarmanlage ist derzeit {{ states.alarm_control_panel.house.state }}.
  async_action: false
